#====================================================================
# Project Info

name: ataa
description: "description_project_x"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4+7

#====================================================================
# Flutter Version

environment:
  sdk: ^3.5.4

#====================================================================
# Dependencies

dependencies:
  flutter:
    sdk: flutter

  #-------------------------------------
  ## Basic
  get: any
  intl: any
  package_info_plus: any

  #-------------------------------------
  ## Network
  http: ^1.2.0
  url_launcher: any
  universal_html: any

  #-------------------------------------
  ## Map
  google_maps_flutter: any
  maps_toolkit: any

  #-------------------------------------
  ## Animation
  simple_animations: any

  #-------------------------------------
  ## Locale Data
  hive: any
  path_provider: any

  ##-------------------------------------
  ## Icons
  iconsax: any
  cupertino_icons: any
  material_design_icons_flutter: ^7.0.7296

  ##-------------------------------------
  ## Video
  video_player: ^2.9.2
  chewie: ^1.8.5
  youtube_player_flutter: ^9.1.1

  ##-------------------------------------
  ## Image
  image_picker: any
  image_network: ^2.5.1
  flutter_svg: ^2.0.9 # To support SVG images

  ##-------------------------------------
  ## Features
  quick_actions: ^1.0.7

  #-------------------------------------
  ## Text
  flutter_widget_from_html: ^0.15.2

  #-------------------------------------
  ## Firebase
  firebase_core: any
  firebase_analytics: any
  firebase_remote_config: any
  firebase_crashlytics: any

  #-------------------------------------
  ## pay
  pay: ^2.0.0

  #-------------------------------------
  ## image
  image_gallery_saver_plus: any

  #-------------------------------------
  ## widget
  badges: ^3.1.2 # Notice number on the icon
  flutter_spinbox: ^0.13.1 # Number entry widget
  auto_size_text: ^3.0.0 # Automatic text size
  smooth_page_indicator: ^1.1.0 # Show the number of images and any open image via dots below the image
  flutter_advanced_segment: ^3.0.2 # Multiple tabs item

  #-------------------------------------
  ## Other
  flutter_native_contact_picker: ^0.0.9 # To fetch data from contacts
  sms_autofill: ^2.4.1 # OTP sms auto fill
  webview_flutter: ^4.9.0
  flex_list: ^1.0.0
  permission_handler: any
  downloadsfolder: ^1.1.1
  app_links: ^6.3.3
#  flutter_share_me: ^1.3.0 # To share links externally

  #-------------------------------------
  ## Edit Package
  flutter_multi_formatter: ^2.12.4
  country_flags: ^2.2.0
  json_annotation: ^4.8.1
  flutter_rating_bar: ^4.0.1

#====================================================================
# Dev Dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
#  flutter_native_splash: any

#====================================================================
# Splash Screen

flutter_native_splash:
  color: '#0E6863'
  image:  assets/splash/splash.png
  color_dark: '#0E6863'
  image_dark: assets/splash/splash.png
  android_12:
    color: '#0E6863'
    image: assets/splash/splash.png
    color_dark: '#0E6863'
    image_dark: assets/splash/splash.png
  fullscreen: true
  android: true
  ios: true
#  flutter pub run flutter_native_splash:create

#====================================================================
# Assets

flutter:
  uses-material-design: true
  #-------------------------------------
  ## Images & Icons

  assets:
    # pubspec.yaml: It must be present to access package data, application name and version
    - pubspec.yaml
    - assets/images/
    - assets/images/flags/
    - assets/images/logos/
    - assets/images/otherLogos/
    - assets/images/empty/
    - assets/images/creditCard/
    - assets/images/gift/
    - assets/images/rate/
    - assets/images/other/
    - assets/icons/
    - assets/splash/
    - assets/fonts/
    - assets/paymentConfiguration/

  #-------------------------------------
  ## Fonts

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700

    - family: Icon_x
      fonts:
        - asset: assets/fonts/Icon_x.ttf